[[constraint]]
  name = "github.com/devlocker/devproxy"
  version = "0.2.2"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
